before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: p6DbOraguA6JtcLiwnLiEg1cRTu3UrjdNomlLdI2EbH1zbkzIYj8vjN4ztR7a5Rpr/DzQiSW2zZWrMMRwQvEizwjOPyYETaERYw+ozsZxdky8zNzdfkK0DWOPq74vHyXB7zwBP3XFpM9GO0wM6B+hn2TZhFzQ2bNFgHC9Gf3Pj7wGaGZhIi0iF8c8kfCO7f1WMMWgV8pdhkw12Euo2Baqqnl13kXCRDz6x3mzJafhpVHuQaKtTX+sEN16YuWUlET6GLcZ7lQeJFseUHK2diVJchEbuEXlQs2emF7rtlj2qVXk41ECl55jMxf02NTF6K385mh3XIp+sbRtw3Ytf5ir1sQRz3YnLsxD9KzSj/mqozS4OUe75XB16DYvPoU7A2NtpFpvutmVFRdsNDngnLYRI6ueuteGH6GDSalVttjPWY9or8eaqEjXBB4JpqbgogMXY3u0URY6GyvT5pBtJMwBEjnpP6jme5kh6uqowt/clqtmYoRT4GW0cI8M2pJSz7DdXE4CatJMWpT6BONFxm8o7BGjHaJcXu4MlrHhE1JJ9YlYNHVZ5uanFntPFhSWimZhalJDXdDSX2cRGQ65Pz15Gbh9gmvka22XyStaE3k5xVF5+dDPctZwZAytxtC/fElBR86HUTghuxXs1GKp5+O5qbhN0DPaF3sa/SYqJra1Cs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
